import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    "nav.home": "Home",
    "nav.about": "About Us",
    "nav.products": "Products",
    "nav.gallery": "Gallery",
    "nav.contact": "Contact",
    "nav.orderNow": "Order Now 🛒",

    "hero.tag": "100% NATURAL & FARM FRESH · TASGAON",
    "hero.title1": "From Our Farm,",
    "hero.title2": "To Your Family",
    "hero.desc": "Premium quality Grapes, Mangoes & Guavas grown naturally with love and care at Kusarkar Farm.",
    "hero.btnExplore": "Explore Products ➔",
    "hero.btnContact": "Contact Us 📞",
    "hero.rating": "500+ Direct Orders",
    "hero.f1Title": "Natural Farming",
    "hero.f1Sub": "Chemical Free",
    "hero.f2Title": "Farm Fresh",
    "hero.f2Sub": "Daily Harvest",
    "hero.f3Title": "Premium Quality",
    "hero.f3Sub": "Best Selection",

    "ff.grapesTitle": "Grapes",
    "ff.grapesSub": "Sweet & Fresh",
    "ff.mangoTitle": "Mango",
    "ff.mangoSub": "Juicy & Natural",
    "ff.guavaTitle": "Guava",
    "ff.guavaSub": "Fresh & Healthy",
    "ff.viewMore": "View More ➔",

    "prod.eyebrow": "🍃 OUR PRODUCTS",
    "prod.sectionTitle": "🍃 Our Premium Fruits 🍃",
    "prod.sectionSub": "Handpicked with care, delivered with love",
    "prod.grapesTitle": "Grapes",
    "prod.grapes1": "Sweet & Crunchy",
    "prod.grapes2": "Export Quality",
    "prod.grapes3": "Naturally Grown",
    "prod.grapes4": "Rich in Antioxidants",
    "prod.mangoTitle": "Mango",
    "prod.mango1": "Naturally Ripened",
    "prod.mango2": "Juicy & Sweet",
    "prod.mango3": "Premium Quality",
    "prod.mango4": "Seasonal Delight",
    "prod.guavaTitle": "Guava",
    "prod.guava1": "Vitamin C Rich",
    "prod.guava2": "Chemical Free",
    "prod.guava3": "Organic Farming",
    "prod.guava4": "Fresh Harvest",
    "prod.addCart": "Add to Cart 🛒",

    "about.eyebrow": "About",
    "about.titleMain1": "About",
    "about.titleMain2": "Kusarkar Farm",
    "about.tag": "🍃 ABOUT KUSARKAR FARM",
    "about.title1": "Growing Nature",
    "about.title2": "With Passion",
    "about.desc": "For over 15 years, we have been dedicated to natural farming, producing high-quality fruits with care and love. Our fruits are freshly harvested and delivered straight from our farm to your family.",
    "about.btn": "Know More About Us ➔",
    "about.stat1": "Years Experience",
    "about.stat2": "Happy Customers",
    "about.stat3": "Acres of Farm",
    "about.stat4": "Fruits Delivered",

    "gallery.eyebrow": "📸 FARM GALLERY",
    "gallery.title": "Our Farm Gallery 🍃",
    "gallery.btn": "View More Photos",

    "why.eyebrow": "🌿 WHY US",
    "why.title": "Why Choose Kusarkar Farm?",
    "why.c1Title": "100% Farm Fresh",
    "why.c1Sub": "Direct From Farm",
    "why.c2Title": "Naturally Grown",
    "why.c2Sub": "Chemical Free",
    "why.c3Title": "Handpicked Fruits",
    "why.c3Sub": "Carefully Selected",
    "why.c4Title": "Premium Quality",
    "why.c4Sub": "Best in Taste",
    "why.c5Title": "Hygienic Packaging",
    "why.c5Sub": "Safe & Clean",
    "why.c6Title": "Direct From Farm",
    "why.c6Sub": "No Middlemen",
    "why.c7Title": "Affordable Price",
    "why.c7Sub": "Best Value",
    "why.c8Title": "Rich Taste",
    "why.c8Sub": "Naturally Sweet",

    "contact.badge": "📍 Get In Touch",
    "contact.title1": "Visit",
    "contact.title2": "Kusarkar Farm – Krushi Samrajya",
    "contact.sub": "Connect with us for farm visits, fresh orders, or bulk inquiries",
    "contact.formTitle": "Send Us A Message",
    "contact.nameLabel": "Your Name *",
    "contact.phoneLabel": "Phone Number *",
    "contact.emailLabel": "Email Address",
    "contact.msgLabel": "Your Requirement / Message",
    "contact.msgPlaceholder": "Tell us what fruits or quantity you need...",
    "contact.btnSend": "Send Message 💬",
    "contact.krushiBadge": "🍇 Krushi Samrajya",
    "contact.farmHeading": "Kusarkar Farm",
    "contact.farmTag": "Tasgaon, Dist. Sangli | Direct From Farm",
    "contact.addrTitle": "Farm Address",
    "contact.addrDesc": "Landghol Mala, Tasgaon, Taluka Tasgaon, Dist. Sangli - 416312",
    "contact.timeTitle": "Visiting & Order Hours",
    "contact.timeDesc": "Mon – Sun: 6:00 AM – 9:00 PM",
    "contact.specTitle": "Farm Specialties",
    "contact.specDesc": "Alphonso Mangoes, Grapes & Fresh Guavas",
    "contact.quickConnect": "Quick Connect:",
    "contact.btnCall": "📞 Call Us",
    "contact.btnWa": "💬 WhatsApp",
    "contact.openMaps": "Open Location in Google Maps 📍",
    "contact.getDirections": "Get Driving Directions 🚗",
    "contact.mapHeading": "Kusarkar Farm – Krushi Samrajya",
    "contact.mapSub": "📍 Tasgaon, Taluka Tasgaon, Dist. Sangli",

    "footer.brandName": "Kusarkar Farm",
    "footer.tagline": "From Our Farm, To Your Family",
    "footer.quickLinks": "Quick Links",
    "footer.ourProducts": "Our Products",
    "footer.followUs": "Follow Us",
    "footer.rights": "© 2025 Kusarkar Farm. All rights reserved.",

    "cart.title": "🛒 Your Cart",
    "cart.empty": "Your cart is empty",
    "cart.emptySub": "Add some fresh fruits!",
    "cart.subtotal": "Subtotal",
    "cart.delivery": "Delivery",
    "cart.free": "FREE",
    "cart.total": "Total",
    "cart.btnCheckout": "📦 Place Order via WhatsApp",
    "cart.btnClear": "Clear Cart"
  },
  mr: {
    "nav.home": "मुखपृष्ठ",
    "nav.about": "आमच्याबद्दल",
    "nav.products": "उत्पादने",
    "nav.gallery": "गॅलरी",
    "nav.contact": "संपर्क",
    "nav.orderNow": "ऑर्डर करा 🛒",

    "hero.tag": "१००% नैसर्गिक व फार्म फ्रेश · तासगाव",
    "hero.title1": "आमच्या शेतातून,",
    "hero.title2": "थेट तुमच्या कुटुंबापर्यंत",
    "hero.desc": "कुसरकर फार्ममध्ये प्रेमाने व काळजीने नैसर्गिकरीत्या पिकवलेली उत्तम दर्जाची द्राक्षे, आंबे आणि पेरू.",
    "hero.btnExplore": "उत्पादने पहा ➔",
    "hero.btnContact": "संपर्क साधा 📞",
    "hero.rating": "५००+ थेट ऑर्डर्स",
    "hero.f1Title": "नैसर्गिक शेती",
    "hero.f1Sub": "रासायनिक खतमुक्त",
    "hero.f2Title": "फार्म फ्रेश",
    "hero.f2Sub": "दररोजची काढणी",
    "hero.f3Title": "प्रीमियम गुणवत्ता",
    "hero.f3Sub": "उत्कृष्ट निवड",

    "ff.grapesTitle": "द्राक्षे",
    "ff.grapesSub": "गोड व ताजी",
    "ff.mangoTitle": "आंबा",
    "ff.mangoSub": "रसाळ व नैसर्गिक",
    "ff.guavaTitle": "पेरू",
    "ff.guavaSub": "ताजे व पौष्टिक",
    "ff.viewMore": "अधिक पहा ➔",

    "prod.eyebrow": "🍃 आमची उत्पादने",
    "prod.sectionTitle": "🍃 आमची खास फळे 🍃",
    "prod.sectionSub": "काळजीपूर्वक निवडलेली, प्रेमाने पोहोचवलेली",
    "prod.grapesTitle": "द्राक्षे",
    "prod.grapes1": "गोड व कुरकुरीत",
    "prod.grapes2": "एक्सपोर्ट क्वालिटी",
    "prod.grapes3": "नैसर्गिकरीत्या पिकवलेली",
    "prod.grapes4": "अँटीऑक्सिडंट्सने समृद्ध",
    "prod.mangoTitle": "आंबा",
    "prod.mango1": "नैसर्गिक रीतीने पिकवलेले",
    "prod.mango2": "रसाळ व गोड",
    "prod.mango3": "प्रीमियम गुणवत्ता",
    "prod.mango4": "हंगामातील मेजवानी",
    "prod.guavaTitle": "पेरू",
    "prod.guava1": "व्हिटॅमिन सी ने समृद्ध",
    "prod.guava2": "केमिकल फ्री",
    "prod.guava3": "सेंद्रिय शेती",
    "prod.guava4": "ताजी काढणी",
    "prod.addCart": "कार्टमध्ये जोडा 🛒",

    "about.eyebrow": "आमच्याबद्दल",
    "about.titleMain1": "कुसरकर",
    "about.titleMain2": "फार्मबद्दल",
    "about.tag": "🍃 कुसरकर फार्मबद्दल",
    "about.title1": "निसर्गाची जपणूक",
    "about.title2": "प्रेमाने व निष्ठेने",
    "about.desc": "गेल्या १५ वर्षांहून अधिक काळ आम्ही नैसर्गिक शेतीसाठी समर्पित आहोत, प्रेमाने व काळजीने उच्च दर्जाची फळे पिकवत आहोत. आमची फळे ताज्या स्वरूपात थेट आमच्या शेतातून तुमच्या घरापर्यंत पोहोचवली जातात.",
    "about.btn": "आमच्याबद्दल अधिक जाणा ➔",
    "about.stat1": "वर्षांचा अनुभव",
    "about.stat2": "आनंदी ग्राहक",
    "about.stat3": "एकरांचे फार्म",
    "about.stat4": "फळांची डिलिव्हरी",

    "gallery.eyebrow": "📸 फार्म गॅलरी",
    "gallery.title": "आमची फार्म गॅलरी 🍃",
    "gallery.btn": "अधिक फोटो पहा",

    "why.eyebrow": "🌿 कुसरकर फार्म का?",
    "why.title": "कुसरकर फार्म का निवडावे?",
    "why.c1Title": "१००% फार्म फ्रेश",
    "why.c1Sub": "थेट शेतातून",
    "why.c2Title": "नैसर्गिकरीत्या पिकवलेले",
    "why.c2Sub": "रसायनमुक्त",
    "why.c3Title": "हाताने निवडलेली फळे",
    "why.c3Sub": "काळजीपूर्वक निवडलेली",
    "why.c4Title": "प्रीमियम गुणवत्ता",
    "why.c4Sub": "उत्कृष्ट चव",
    "why.c5Title": "हायजिनिक पॅकेजिंग",
    "why.c5Sub": "सुरक्षित व स्वच्छ",
    "why.c6Title": "थेट फार्ममधून",
    "why.c6Sub": "मध्यस्थ नाही",
    "why.c7Title": "परवडणारी किंमत",
    "why.c7Sub": "उत्तम मूल्य",
    "why.c8Title": "उत्कृष्ट चव",
    "why.c8Sub": "नैसर्गिकरीत्या गोड",

    "contact.badge": "📍 संपर्क साधा",
    "contact.title1": "भेट द्या",
    "contact.title2": "कुसरकर फार्म - कृषी साम्राज्य",
    "contact.sub": "शेताला भेट देण्यासाठी, ताज्या ऑर्डर्ससाठी किंवा मोठ्या प्रमाणात चौकशीसाठी आमच्याशी संपर्क साधा",
    "contact.formTitle": "आम्हाला मेसेज पाठवा",
    "contact.nameLabel": "तुमचे नाव *",
    "contact.phoneLabel": "मोबाईल नंबर *",
    "contact.emailLabel": "ईमेल पत्ता",
    "contact.msgLabel": "तुमची गरज / मेसेज",
    "contact.msgPlaceholder": "तुम्हाला कोणती फळे किंवा किती प्रमाण हवे आहे ते सांगा...",
    "contact.btnSend": "मेसेज पाठवा 💬",
    "contact.krushiBadge": "🍇 कृषी साम्राज्य",
    "contact.farmHeading": "कुसरकर फार्म",
    "contact.farmTag": "तासगाव, जि. सांगली | थेट शेतातून",
    "contact.addrTitle": "फार्मचा पत्ता",
    "contact.addrDesc": "लांडघोल माळा, तासगाव, ता. तासगाव, जि. सांगली - ४१६३१२",
    "contact.timeTitle": "भेट व ऑर्डर वेळ",
    "contact.timeDesc": "सोम - रवि: सकाळी ६:०० - रात्री ९:००",
    "contact.specTitle": "फार्मची वैशिष्ट्ये",
    "contact.specDesc": "हापूस आंबे, द्राक्षे आणि ताजे पेरू",
    "contact.quickConnect": "झटपट संपर्क:",
    "contact.btnCall": "📞 कॉल करा",
    "contact.btnWa": "💬 व्हॉट्सअ‍ॅप",
    "contact.openMaps": "गूगल मॅप्सवर लोकेशन पहा 📍",
    "contact.getDirections": "रस्ता व मार्ग शोधा (Directions) 🚗",
    "contact.mapHeading": "कुसरकर फार्म - कृषी साम्राज्य",
    "contact.mapSub": "📍 तासगाव, ता. तासगाव, जि. सांगली",

    "footer.brandName": "कुसरकर फार्म",
    "footer.tagline": "आमच्या शेतातून, थेट तुमच्या कुटुंबापर्यंत",
    "footer.quickLinks": "जलद लिंक्स",
    "footer.ourProducts": "आमची उत्पादने",
    "footer.followUs": "आम्हाला फॉलो करा",
    "footer.rights": "© २०२५ कुसरकर फार्म. सर्व हक्क राखीव.",

    "cart.title": "🛒 तुमची कार्ट",
    "cart.empty": "तुमची कार्ट रिकामी आहे",
    "cart.emptySub": "काही ताजी फळे जोडा!",
    "cart.subtotal": "सबटोटल",
    "cart.delivery": "डिलिव्हरी",
    "cart.free": "मोफत",
    "cart.total": "एकूण",
    "cart.btnCheckout": "📦 व्हॉट्सअ‍ॅपद्वारे ऑर्डर द्या",
    "cart.btnClear": "कार्ट रिकामी करा"
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => localStorage.getItem('kf-lang') || 'en');

  useEffect(() => {
    localStorage.setItem('kf-lang', lang);
  }, [lang]);

  const toggleLanguage = () => {
    setLang(prev => (prev === 'en' ? 'mr' : 'en'));
  };

  const t = (key) => {
    return translations[lang]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
