import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    "nav.home": "Home",
    "nav.about": "About Us",
    "nav.products": "Products",
    "nav.gallery": "Gallery",
    "nav.contact": "Contact",
    "nav.orderNow": "Order Now 🛒",
    "hero.tag": "100% NATURAL & CHEMICAL FREE",
    "hero.title1": "Fresh From Nature,",
    "hero.title2": "Made For You.",
    "hero.desc": "Premium quality Grapes, Mangoes & Guavas grown naturally with care at Kusarkar Farm.",
    "hero.btnExplore": "Explore Products ➔",
    "hero.btnContact": "Contact Us 📞",
    "hero.f1Title": "Farm Fresh",
    "hero.f1Sub": "Daily Harvest",
    "hero.f2Title": "Natural Farming",
    "hero.f2Sub": "Chemical Free",
    "hero.f3Title": "Premium Quality",
    "hero.f3Sub": "Best Selection",
    "hero.f4Title": "Direct From Farm",
    "hero.f4Sub": "To Your Home",
    "ff.grapesTitle": "Grapes",
    "ff.grapesSub": "Sweet & Fresh",
    "ff.mangoTitle": "Mango",
    "ff.mangoSub": "Juicy & Natural",
    "ff.guavaTitle": "Guava",
    "ff.guavaSub": "Fresh & Healthy",
    "ff.viewMore": "View More ➔",
    "prod.sectionTitle": "🍃 Our Premium Fruits 🍃",
    "prod.sectionSub": "Handpicked with care, delivered with love",
    "prod.grapesTitle": "Grapes",
    "prod.mangoTitle": "Mango",
    "prod.guavaTitle": "Guava",
    "prod.addCart": "Add to Cart 🛒",
    "about.tag": "🌱 OUR STORY",
    "about.title1": "Cultivating Freshness",
    "about.title2": "Since Generations",
    "about.desc": "At Kusarkar Farm, we believe in sustainable and natural farming practices. Nestled in Tasgaon, Sangli, our orchards produce the finest Alphonso Mangoes, Black Grapes, and Guavas.",
    "about.btn": "Learn More About Us",
    "about.stat1": "Years of Experience",
    "about.stat2": "Happy Direct Customers",
    "about.stat3": "Acres of Green Farm",
    "about.stat4": "Orders Delivered",
    "gallery.title": "📸 Farm Photo Gallery",
    "gallery.btn": "View More Shots",
    "why.title": "Why Choose Kusarkar Farm",
    "why.c1Title": "100% Organic",
    "why.c1Sub": "No harmful chemicals",
    "why.c2Title": "Farm Fresh",
    "why.c2Sub": "Harvested daily",
    "why.c3Title": "Direct Harvest",
    "why.c3Sub": "From Tasgaon farm",
    "why.c4Title": "Premium Quality",
    "why.c4Sub": "Handpicked selection",
    "why.c5Title": "Safe Packaging",
    "why.c5Sub": "Eco-friendly box",
    "why.c6Title": "Farmer Direct",
    "why.c6Sub": "No middleman margin",
    "why.c7Title": "Best Rates",
    "why.c7Sub": "Fair & affordable",
    "why.c8Title": "Fast Shipping",
    "why.c8Sub": "Doorstep delivery",
    "contact.badge": "GET IN TOUCH",
    "contact.title1": "Visit Kusarkar Farm –",
    "contact.title2": "Krushi Samrajya",
    "contact.sub": "Have a question or want to place a custom order? Send us a message below or visit our farm!",
    "contact.formTitle": "Send Us a Message",
    "contact.nameLabel": "Your Name *",
    "contact.phoneLabel": "Phone Number *",
    "contact.emailLabel": "Email Address",
    "contact.msgLabel": "Message / Order Details",
    "contact.btnSend": "Send Enquiry via WhatsApp 💬",
    "contact.farmTag": "Organic Farming & Direct Fruit Sales",
    "contact.addrTitle": "Farm Address",
    "contact.addrDesc": "Kusarkar Farm – Krushi Samrajya, Tasgaon, Taluka Tasgaon, District Sangli, Maharashtra – 416312",
    "contact.timeTitle": "Farm Visiting Hours",
    "contact.timeDesc": "Monday – Sunday: 8:00 AM – 7:00 PM",
    "contact.specTitle": "Our Specialties",
    "contact.specDesc": "Export Quality Grapes, Alphonso Mangoes & Fresh Guavas",
    "contact.quickConnect": "Quick Connect:",
    "contact.btnCall": "📞 Call: 9421311949",
    "contact.btnWa": "💬 WhatsApp Us",
    "contact.openMaps": "🗺️ Open Location in Google Maps",
    "footer.tagline": "Direct harvest Alphonso Mangoes, Black Grapes & Guavas from Tasgaon, Sangli.",
    "footer.quickLinks": "Quick Links",
    "footer.ourProducts": "Our Fruits",
    "footer.followUs": "Follow Us",
    "footer.rights": "© 2026 Kusarkar Farm - Krushi Samrajya. All rights reserved.",
    "cart.title": "Your Shopping Cart 🛒",
    "cart.empty": "Your cart is currently empty",
    "cart.emptySub": "Add some fresh fruits from above!",
    "cart.subtotal": "Subtotal",
    "cart.delivery": "Delivery",
    "cart.free": "FREE",
    "cart.total": "Total Amount",
    "cart.btnCheckout": "Proceed to WhatsApp Order 📦",
    "cart.btnClear": "Clear Cart"
  },
  mr: {
    "nav.home": "मुखपृष्ठ",
    "nav.about": "आमच्याबद्दल",
    "nav.products": "उत्पादने",
    "nav.gallery": "गॅलरी",
    "nav.contact": "संपर्क",
    "nav.orderNow": "ऑर्डर करा 🛒",
    "hero.tag": "१००% नैसर्गिक व केमिकल फ्री",
    "hero.title1": "निसर्गातून ताजं,",
    "hero.title2": "विशेष तुमच्यासाठी.",
    "hero.desc": "कुसरकर फार्ममध्ये प्रेमाने व काळजीने नैसर्गिकरीत्या पिकवलेली उत्तम दर्जाची द्राक्षे, आंबे आणि पेरू.",
    "hero.btnExplore": "उत्पादने पहा ➔",
    "hero.btnContact": "संपर्क साधा 📞",
    "hero.f1Title": "फार्म फ्रेश",
    "hero.f1Sub": "दररोजची काढणी",
    "hero.f2Title": "नैसर्गिक शेती",
    "hero.f2Sub": "रासायनिक खतमुक्त",
    "hero.f3Title": "प्रीमियम गुणवत्ता",
    "hero.f3Sub": "उत्कृष्ट निवड",
    "hero.f4Title": "शेतातून थेट",
    "hero.f4Sub": "तुमच्या घरापर्यंत",
    "ff.grapesTitle": "द्राक्षे",
    "ff.grapesSub": "गोड व ताजी",
    "ff.mangoTitle": "आंबा",
    "ff.mangoSub": "रसाळ व नैसर्गिक",
    "ff.guavaTitle": "पेरू",
    "ff.guavaSub": "ताजे व निरोगी",
    "ff.viewMore": "अधिक पहा ➔",
    "prod.sectionTitle": "🍃 आमची ताजी उत्पादने 🍃",
    "prod.sectionSub": "काढणीपासून थेट तुमच्या दारापर्यंत",
    "prod.grapesTitle": "द्राक्षे",
    "prod.mangoTitle": "आंबा",
    "prod.guavaTitle": "पेरू",
    "prod.addCart": "कार्टमध्ये जोडा 🛒",
    "about.tag": "🌱 आमची कथा",
    "about.title1": "पिढ्यानपिढ्या जपलेली",
    "about.title2": "शेतीची परंपरा",
    "about.desc": "कुसरकर फार्ममध्ये आम्ही नैसर्गिक आणि शाश्वत शेतीवर विश्वास ठेवतो. तासगाव, सांगली येथील आमच्या बागांमध्ये उत्तम हापूस आंबे, काळी द्राक्षे आणि पेरू पिकवले जातात.",
    "about.btn": "अधिक माहिती मिळवा",
    "about.stat1": "वर्षांचा अनुभव",
    "about.stat2": "समाधानी ग्राहक",
    "about.stat3": "एकड हिरवीगार बाग",
    "about.stat4": "पूर्ण झालेल्या ऑर्डर्स",
    "gallery.title": "📸 बागेचे छायाचित्र दालन",
    "gallery.btn": "अधिक फोटो पहा",
    "why.title": "कुसरकर फार्म का निवडावे?",
    "why.c1Title": "१००% सेंद्रिय",
    "why.c1Sub": "केमिकल्स विरहित शेती",
    "why.c2Title": "ताजी काढणी",
    "why.c2Sub": "दररोज ताजी फळे",
    "why.c3Title": "तासगाव बाग",
    "why.c3Sub": "थेट शेतातून विक्री",
    "why.c4Title": "उत्कृष्ट गुणवत्ता",
    "why.c4Sub": "निवडक व दर्जेदार फळे",
    "why.c5Title": "सुरक्षित पॅकिंग",
    "why.c5Sub": "इको-फ्रेंडली बॉक्स",
    "why.c6Title": "शेतकरी दर",
    "why.c6Sub": "मध्यस्थांशिवाय विक्री",
    "why.c7Title": "रास्त किमती",
    "why.c7Sub": "सर्वांना परवडणारे",
    "why.c8Title": "जलद डिलिव्हरी",
    "why.c8Sub": "घरापर्यंत पोहोच",
    "contact.badge": "संपर्क साधा",
    "contact.title1": "कुसरकर फार्मला भेट द्या –",
    "contact.title2": "कृषी साम्राज्य",
    "contact.sub": "काही प्रश्न आहेत किंवा ऑर्डर करायची आहे? खालील फॉर्म भरा किंवा थेट आमच्या बागेला भेट द्या!",
    "contact.formTitle": "मेसेज पाठवा",
    "contact.nameLabel": "तुमचे नाव *",
    "contact.phoneLabel": "फोन नंबर *",
    "contact.emailLabel": "ईमेल आयडी",
    "contact.msgLabel": "मेसेज / ऑर्डर तपशील",
    "contact.btnSend": "WhatsApp द्वारे मेसेज पाठवा 💬",
    "contact.farmTag": "सेंद्रिय शेती व थेट फळ विक्री केंद्र",
    "contact.addrTitle": "शेताचा पत्ता",
    "contact.addrDesc": "कुसरकर फार्म - कृषी साम्राज्य, तासगाव, तालुका तासगाव, जिल्हा सांगली, महाराष्ट्र - ४१६३१२",
    "contact.timeTitle": "भेट देण्याची वेळ",
    "contact.timeDesc": "सोमवार - रविवार: सकाळी ८:०० ते संध्याकाळी ७:००",
    "contact.specTitle": "आमची वैशिष्ट्ये",
    "contact.specDesc": "एक्सपोर्ट क्वालिटी द्राक्षे, हापूस आंबे आणि ताजे पेरू",
    "contact.quickConnect": "त्वरित संपर्क:",
    "contact.btnCall": "📞 कॉल करा: 9421311949",
    "contact.btnWa": "💬 WhatsApp वर बोला",
    "contact.openMaps": "🗺️ गूगल मॅपवर लोकेशन पहा",
    "footer.tagline": "तासगाव सांगली येथून थेट हापूस आंबे, काळी द्राक्षे व पेरू.",
    "footer.quickLinks": "महत्त्वाच्या लिंक्स",
    "footer.ourProducts": "आमची फळे",
    "footer.followUs": "सोशल मीडिया",
    "footer.rights": "© २०२६ कुसरकर फार्म - कृषी साम्राज्य. सर्व हक्क सुरक्षित.",
    "cart.title": "तुमची शॉपिंग कार्ट 🛒",
    "cart.empty": "तुमची कार्ट सध्या रिकामी आहे",
    "cart.emptySub": "वर दिलेल्या उत्पादनांमधून फळे जोडा!",
    "cart.subtotal": "एकूण किंमत",
    "cart.delivery": "डिलिव्हरी शुल्क",
    "cart.free": "मोफत",
    "cart.total": "अंतिम रक्कम",
    "cart.btnCheckout": "WhatsApp वर ऑर्डर पाठवा 📦",
    "cart.btnClear": "कार्ट रिकामी करा"
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('kf-lang') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('kf-lang', lang);
  }, [lang]);

  const toggleLanguage = () => {
    setLang(prev => (prev === 'en' ? 'mr' : 'en'));
  };

  const t = (key) => {
    return translations[lang]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
